// PRODUCT
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const CHANGE_PRODUCT = "CHANGE_PRODUCT";

// USER
export const GET_SELECTED_USER = "GET_SELECTED_USER";
export const CHANGE_TOP = "CHANGE_TOP";
export const USER_START = 'USER_START';
export const USER_ME = 'USER_ME';
export const USER_FAILED = 'USER_FAILED';

// LMS
export const PRODUCT_START = 'PRODUCT_START';
export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_BY_ID = 'PRODUCT_BY_ID';
export const PRODUCT_FAILED = 'PRODUCT_FAILED';

// CONTENT
export const CONTENT_START = 'CONTENT_START';
export const CONTENT_VIDEO_LIST = 'CONTENT_VIDEO_LIST';
export const CONTENT_VIDEO_BY_ID = 'CONTENT_VIDEO_BY_ID';
export const CONTENT_BLOG_LIST = 'CONTENT_BLOG_LIST';
export const CONTENT_BLOG_BY_ID = 'CONTENT_BLOG_BY_ID';
export const CONTENT_FAILED = 'CONTENT_FAILED';

// REVIEW
export const REVIEW_START = 'REVIEW_START';
export const REVIEW_SUCCESS = 'REVIEW_SUCCESS';
export const REVIEW_BY_USER_PER_PRODUCT = 'REVIEW_BY_USER_PER_PRODUCT';
export const REVIEW_FAILED = 'REVIEW_FAILED';

// ORDER
export const ORDER_START = 'ORDER_START';
export const ORDER_PAID_LIST = 'ORDER_PAID_LIST';
export const ORDER_FAILED = 'ORDER_FAILED';
